---
title: The More Important Problem
date: '2019-03-09'
author: "Derek Willis"
format:
  html:
    df-print: paged
    toc: true
engine: knitr
---

The first indication that I did not approach this [NICAR-L improvement project](http://thescoop.org/archives/2019/02/24/making-the-best-nicar-listserv/) in the right way should have been when I posted on GitHub a CSV file with metadata from 16 years' of posts to the listserv. Not long after, I got a message saying that maybe I should take it down because it disclosed individuals' email addresses.

"Huh," I thought. "Why would it be a problem for journalists' emails to be public?" I asked myself, a guy who has been on the listserv for more than 20 years whose worst experience on it consists of people I respect dunking on me in a way that I wouldn't object to. The social and professional risk of posting on the listserv is low for me, but not for everyone. The Internet, by and large, has been a pretty safe place for me, but not for everyone.

If I needed any reinforcement of that initial indication, it came when I looked at the small group of people who showed up at [the conference session](https://www.ire.org/events-and-training/event/3433/4362/) to talk about ways to improve the listserv experience. The folks who came -- all good, smart people -- had this much in common: they were, like me, white guys. I had billed the session as an attempt to explore technical solutions that would make the listserv more useful for its expanding community of users. Maybe even a chance to restore the listserv's culture to what it had been in the days when the community numbered in the hundreds, not the thousands. You know, when it was mostly guys like me who shared a lot of the same experiences.

That I had not really thought much about how different people experience the listserv differently says a lot about the actual challenge we face in trying to make NICAR-L more useful for everyone (and something about me, too). The easier lesson is that technical solutions may be necessary to achieve the goal of a better listserv, but they are not sufficient. The harder - and more important - lesson is that if we want things to improve, we'll need to think hard about what factors into individual decisions to post and not post, and what kind of community we want. Otherwise the technical work won't be addressing the more important problem.

There's a [Google doc](https://docs.google.com/document/d/13QdI3J8GQm-ECFsQx6Bllwrz2epZ6BXdtV2bsRAQxeI/edit?usp=sharing) from our initial discussion that includes some potential goals and ideas we talked about. All of them are possible and many of them could make a real difference, even if only in a small way. I don't think any of them are outlandish or techno-utopianism run amok. (You can, if you like, comment on them.)

But the idea that we could make fundamental improvements in the listserv experience without addressing the culture that surrounds it is folly. We can't recommend NICAR-L to students and newcomers and then expect them to magically know how to adjust to whatever tone and culture they find if we don't define the culture we want and build the processes that encourage it. We also can't consider the listserv in isolation. The NICAR crowd has other options for sharing knowledge and building community, from Slack to affinity groups, and those are unlikely to disappear. Those competitors might help inform how we consider the listserv, too.

So what's the current culture of NICAR-L? I'm not sure I have a good answer, because my own perception is influenced by how I experienced it 15-20 years ago. One of the participants at the conference session said he doesn't post because he's not sure who is on the listserv. When I was an active participant that wasn't a concern for me. Now, I get the sense that NICAR-L is not as homogenous as it was (which is a good thing for many reasons) and that there's also greater uncertainty about what the listserv is for and what people should expect from it. That's a shame, because I really believe that there is a lot of value not just in the archives but in the current membership. But in my excitement about the possibilities, I looked right past the idea that human problems often require human intervention.

Here's what I'm going to do: I'd still like to explore some of the ideas that were raised at the conference session, with the goal of trying to understand the culture of the listserv and how we all react to it. And I'd like to do what I can to encourage all of us to talk about what we want from the listserv and what we need to get there. For me, one step is to re-engage more on the listserv. Ultimately, technology will only make a difference if we have clear understanding of the problems we're trying to solve and if we're willing to have an open conversation about the kind of culture we want to have.
