---
title: The Long Bet
date: 2002-03-25
author: "Derek Willis"
format:
  html:
    df-print: paged
    toc: true
engine: knitr
---

It's Dave Winer vs. the New York Times in a bet over, well, [it's not exactly clear](http://web.archive.org/web/20020803185747/http://www.longbets.org/bet/2). Dave says it's about "which will be authoritative," although that's not what the question itself says - or what the answer to the question will reveal. In fact, I'm quite sure Dave will win the bet, because right now Google is much better at indexing weblogs than the Times. Sort of like picking the judges. And the methodology of the bet itself is suspect. For instance, if we took Dave's suggestion and searched Google for "Enron" today, [Oliver Willis' EnronGate blog](http://web.archive.org/web/20020802045757/http://www.oliverwillis.com/enrongate/index.php) is the 11th result, higher than any Times piece. But guess what? Oliver's top three links are all Times pieces!. So which is more "authoritative," Oliver for pointing to the Times or the Times for printing the story in the first place? Besides, the whole thing can be rigged anyway. But there are other points in Dave's essay that deserve attention and rebuttal.

First, there is little doubt that weblogs do enable individuals with expertise to get that information out to a wider audience. That's a good thing. But the crux of my argument stems from this part of Dave's essay: "This process is fed by the changing economics of the publishing industry which is employing fewer reporters, editors and writers. But the Web has taught us to expect more information, not less, and that's the sea-change that the NY Times and other big publications face -- how to remain relevant in the face of a population that can do for themselves what the BigPubs won't."

Yes, newspapers have been downsizing, although the pattern of hirings and layoffs is a natural cycle for the business. But the real point is that newspapers do things that very few individuals would do on their own for no pay -- extensive investigations that take months and cost thousands of dollars. Some of these investigations are incredibly difficult to accomplish. Would bloggers have footed the bill for [the Florida ballot review](http://www.nytimes.com/pages/politics/recount/index.html)? Would they [risk their lives to uncover corruption](http://ire.org/about/history/)? Would they analyze thousands of records to show how a state board of medicine is failing to protect the public?

My guesses: No, no and no.

I'm reminded of what Phil Meyer told the NICAR conference on March 16. He looked around the room at a small crowd - smaller than the year before, certainly - and asked whether our work was still important, whether now, in a time of budget cutbacks and profit margin pressure, investigative journalism still had a place. His answer? "Now more than ever." In five years our nation and our world will need no less.

News organizations are more than just the people who have been covering the tech industry, and certainly we've made our share of mistakes. But there's a larger picture to consider, and that's where the work of a large news organization like the Times becomes so valuable.

You can define "authoritative" any way you like, I suppose, but I tend to think of it as meaning a message or product that will try to tackle not just the most obvious questions but those below the surface or on the periphery. Will bloggers know all about the Enron of 2007? I have no doubt. Will the Times or some other large newspaper be able to explain it in its entirety - the social, economic and political effects? I fervently believe it. If not, all of us - bloggers and non-bloggers alike, will be the worse for it.
