---
title: Lightning Talks at NICAR
date: 2010-02-18
author: "Derek Willis"
format:
  html:
    df-print: paged
    toc: true
engine: knitr
---

This year's [computer-assisted reporting conference in Phoenix](http://web.archive.org/web/20100419140904/http://data.nicar.org/CAR2010/) has a couple of new sessions on the schedule. [One of them](http://web.archive.org/web/20100419140904/http://data.nicar.org/node/3766) is an idea a couple of us have been pushing for a few years: [lightning talks](http://en.wikipedia.org/wiki/Lightning_Talk).

A staple of technical conferences, lightning talks are based on the notion that while 45-50 minutes presentations are good, sometimes you only need about 5 minutes to express an idea or show off an example of something interesting or useful. And I'm pretty sure, based on sessions at the hotel bar at past conferences, that there are plenty of ideas out there. Attracting and organizing them is the goal of [this app](http://ire.aronpilhofer.com/) built by my boss, Aron Pilhofer, and launched today.

This is a new thing for the CAR community, but I think it could be a useful way to draw out ideas from people who aren't doing panels or who might shrink from a 50-minute session. So let's get started. Want to give a talk?