---
layout: post
title: What I've Been Up To Lately
date: '2012-11-09T15:06:00-05:00'
tags: []
tumblr_url: http://dwillis.net/post/35352508491/what-ive-been-up-to-lately
---
A link dump of election-related work that I’ve contributed to as part of The New York Times’ coverage of the final months of the campaign. In every instance these involved collaborating with at least one other person, and usually more. For most of the stories, it was Nick Confessore and Jo Craven McGinty; for interactive work, it was Jeremy Ashkenas and my colleagues from the Graphics desk.
This collaborative effort is what makes working at The Times so challenging and rewarding; we push each other to bring out our best, and we often save each other from our worst.
Election Night
Presidential, Senate and House Exit Polls (with Josh Keller)
Interactives
Outside Spending in Key House Races (with Kevin Quealy), Oct. 25
2012 Money Race: Compare the Candidates (with Jeremy Ashkenas, Matt Ericson & Alicia Parlapiano)
Super PAC Pages (with Jeremy Ashkenas)
Independent Spending Totals (with Kevin Quealy)
Party Fund-Raising in Battleground States (with Mike Bostock & Kevin Quealy)
The FiveThirtyEight Forecast (the right column of the blog, with Jeremy Ashkenas & David Nolen)
Stories
Last-Minute Money Pours Into Senate Races, Nov. 4
Obama, Romney and Their Parties on Track to Raise $2 Billion, Oct. 25
Romney and Republicans Began Month with $34 Million Advantage, Filings Show, Oct. 20
GOP Congresswoman in Fight To Retain a Hudson Valley Seat, Oct. 18
New Super PACs Alter Landscape for House Races, Oct. 8
In Iowa and Beyond, Redrawn Districts Test Favorites of Tea Party, Oct. 4
New York State Becomes a Focus in the Fight for Congress, Oct. 3
‘Super PACs’ Finally a Draw for Democrats, Sept. 26.
Cash Low, Romney Striving to Find New Large Donors, Sept. 20
And that’s just the stuff that you can see. Behind the scenes, working with my Interactive News colleagues, we’ve built systems to handle the storing and delivery of loads of political and electoral data. Some of that you’ll see more of via Times APIs in the future.
