---
title: "About The Scoop"
---

Hi, I'm Derek Willis, and thescoop.org has been my site since the late 20th century. I teach and do journalism, especially data journalism. I'm a sports geek (a fan of West Indies cricket & Maryland women's basketball), a collector of political data and a reader of non-fiction (sorry, Mom). I don't have a newsletter or a podcast. The image on the home page is from a thank-you note written by a seventh grader after a "Career Day" visit.

### About Me

I was born in Pennsylvania, graduated from the [University of Pittsburgh](http://www.pitt.edu/) with a degree in rhetoric and communications and attended graduate school at the University of Florida (no degree, sorry again Mom). I began my journalism career at [The Palm Beach Post](http://www.pbpost.com/), working in the news library and then as a reporter and technology coordinator. From 1998-2003 I covered Congress and elections for [Congressional Quarterly](http://www.cq.com/). In February 2003 I joined [The Center for Public Integrity](http://www.publicintegrity.org/) as a writer/data specialist working on state and federal projects, where [a report I co-authored](http://www.publicintegrity.org/politics/elections/silent-partners) was honored with a [Sigma Delta Chi award](http://www.spj.org/news.asp?ref=364) by the Society of Professional Journalists. In November 2004 I became the Research Database Editor at the Washington Post; in February 2007 I became Database Editor at washingtonpost.com, and in November 2007 I became an Interactive Developer with The New York Times, working mostly on political and election-related applications and APIs. I joined [The Upshot](https://www.nytimes.com/by/derek-willis) in 2014. From 2015-2021, I worked as a [News Applications Developer at ProPublica](https://www.propublica.org/people/derek-willis).

I was co-editor of CQ’s Federal PACs Directory, published in 1998, and of Unstacking the Deck, a guide to covering campaign finance [published by Investigative Reporters and Editors](http://www.ire.org/resource-center/books/). I’ve been a member of IRE since 1995 and have spoken at numerous conferences and training events around the nation on using the Internet and campaign finance data. I have served as an adjunct faculty member at The George Washington University, Northwestern University and Georgetown University, teaching data reporting classes. I live outside Washington, D.C., with my family. Email me at dwillis AT gmail DOT com.

### Internet Achievements

* [Final winner](http://www.slate.com/articles/news_and_politics/six_degrees_of_francis_bacon/1998/04/_2.single.html) of Slate's "Six Degrees of Francis Bacon" contest, April 18, 1998.
* "[Wanker of the Day](http://www.eschatonblog.com/2006/01/wanker-of-day_17.html)", Atrios, Jan. 17, 2006.
* Cited for [wasting your time](http://www.mediaite.com/tv/jon-stewart-blasts-media-for-wasting-our-time-with-palin-emails/) with Sarah Palin's email by "The Daily Show", June 12, 2011.
* [Dragged by AOC](https://twitter.com/aoc/status/1086396175199207424), Jan. 18, 2019.
