---
title: A Question of Emphasis
date: 2009-11-21
author: "Derek Willis"
format:
  html:
    df-print: paged
    toc: true
engine: knitr
---

The [job cuts at the Washington Post on Friday](http://www.politico.com/blogs/michaelcalderone/1109/Layoffs_at_WaPo_.html) have produced a round of comments, [broadly summed up by Steve Yelvington](https://twitter.com/yelvington/status/5927713381) earlier today. They certainly begged the question that occurred to me as a former employee of both the Post and WPNI, its soon-to-be merged online operation: "What explains this kind of decision?"

First, let me say that my observations about the general history of WPNI and its relationship with the paper are colored by my own experiences, but I agree with folks like [Jay Rosen](https://twitter.com/jayrosen_nyu/status/5921241591) who say that at one point, washingtonpost.com was clearly a national leader – not just in technical capability, but in the kind of mindset necessary for a news organization prepared to take advantage of the Internet's possibilities. I supported the creation of WPNI as a separate operation, to allow it more creative freedom, but both the people of WPNI and their colleagues at the Post should have done more to foster a better environment for working together. It's something that I failed at when I was there.

But back to the kind of environment that leads to the departures, voluntarily or otherwise, of so many talented and dedicated employees. I don't know the people who currently run the Washington Post, but I do think I understand a bit about how the organization works and thinks, having spent about three years there (more than two at the paper and about nine months at WPNI). When I wrote about [moving from the paper to the website back in 2007](http://thescoop.org/archives/2007/02/04/why-the-web/), I left out some details about how that process happened. And I think, in hindsight, that they shed some light on how the organization operates.

It's true that there were a number of people at the Post who were supportive and encouraging of my ambitions to work at WPNI. Among them were my supervisor at the time, Lucy Shackelford, and the paper's editor, Len Downie. But once I had seriously pursued the idea of working on the website, it took months for the move to happen, and not just for reasons of simple corporate bureaucracy. In a very real way, my transition was held up – I (jokingly at first, and then angrily) referred to it as a filibuster or a senatorial hold – by a few people at the paper. These people, most of whom no longer occupy the positions they held then, are not stupid. They are among the smartest folks I've ever worked with, and I have a high regard for their journalistic abilities. But the thinking that _caused the editor of the paper to become involved in whether a mid-level staffer moved to the website_ was, in essence, this: this is a bad idea, because it will hurt the paper. My ego might like to think that this was really true, but I think the reality is that these people could not compare the value of my work for the website to the paper because they did not understand what it is I wanted to do. So they went with what they knew, and that seemed to be a net deficit for them. And thus it was that I mooted the option of simply resigning from the paper in order to join its website.

I don't envy the people who run the Washington Post (or any news organization) today. They have a ton of thankless choices to make, and critics on every side. From a certain standpoint, I can appreciate the idea that the paper edition, which generates the overwhelming share of the revenue, should be protected and bolstered as much as possible. But I cannot agree with the idea that this means that you take employees who have proven expertise doing valuable and informative things that don't always translate into print and cannibalize (or toss away) their talents for the sake of the paper.

My fear as a Washington Post subscriber and reader of washingtonpost.com is that, when the folks running the organization turn things around (and I believe that it is not an impossibility or even a long-shot), what emerges will be not only a news organization that is a shadow of its former self – most orgs will have to face that reality – but that it will have put so much emphasis on the paper that it cannot take advantage of the possibilities online. That the folks running things are literally rolling back the progress and smart work that has been done, and will not be able to get it back as fast as they might think. And the people who remain – those who will be charged with the task of rebuilding a news operation that embraces all of the ways that its readers and users can gain value – will have neither the support nor the depth to make it happen.

