---
title: Our Mark Knoller Problem
date: 2012-05-01
author: "Derek Willis"
format:
  html:
    df-print: paged
    toc: true
engine: knitr
---

My colleagues at The Times (and other folks I know who cover the White House) tell me that [Mark Knoller](http://www.cbsnews.com/8301-18564_162-524942/mark-knoller/), the CBS Radio reporter who reports on the president, is a genuinely nice man and someone who has always been extraordinarily generous about sharing what he knows with other news organizations. Knoller is such a fixture at the White House – he's covered every administration since Gerald Ford's – that he's moved beyond simply being a reporter [into the realm of providing a public service](http://dekerivers.wordpress.com/2011/08/18/meet-cbs-radios-mark-knoller-who-counts-president-obamas-vacation-days/): he's very often cited in other outlets' stories about presidential travel. A sample:

* CBS's Mark Knoller, [who keeps detailed notes on Obama's travels](http://www.huffingtonpost.com/2012/04/25/obama-travel-gop-fraud-complaintl_n_1453713.html), recently told The New York Times that since the president filed for re-election, he's taken 60 domestic trips and 26 of them involved fundraisers.

* But Mark Knoller of CBS, [the unofficial keeper of presidential work schedules](http://www.suntimes.com/news/politics/7127735-418/obamas-vacation-ripped-but-hes-taken-less-time-off-than-bush.html), reported that President George W. Bush had taken more time off than Obama at this point in his first term.

* According to [presidential watcher Mark Knoller of CBS](http://washingtonexaminer.com/politics/washington-secrets/2012/02/michelles-ski-trip-marks-16-obama-vacations/294051), George W. Bush, at this time of his presidency, had made 30 visits to his Texas ranch spanning all or part of 220 days. The Obama's vacation day count is less than half of that.

This isn't about Knoller as a person or as a reporter. It's just that this situation – where one person has become the official source of public knowledge about the travels of the President of the United States – is far from ideal. Forget that the government is occasionally off-base on presidential travel statistics; how is it that other news organizations, including my own, have relied on a system in which one person – however diligent and generous – holds such important information?

From an information management standpoint, having Knoller be the keeper of presidential travel information is not only inefficient – what happens if Knoller is on vacation, or busy? – but makes it harder to regularly review the data or incorporate it into other inquiries. In reality, this is our problem, not Knoller's, and his generosity has enabled us to carry on as if we'd been collecting this information all the time. But we haven't. It's easy enough to just ask Knoller, especially since we don't use the information all that often.

We're not talking about uncovering classified information here, but the daily whereabouts of the President of the United States. And yet somehow, every other news organization has decided that it's perfectly ok not to have this information at its fingertips. It probably won't happen as long as Knoller remains in his job, but what happens if someday CBS decides not to share that information anymore? Or Knoller decides he's tired of doing this and retires? In the "weak link in the chain" scenario, the rest of us are the weak links, not him. He's doing his part. Why are we shirking ours?