---
title: "What I Did Then"
description: "An archive of my previous work"
---

Most of my previous work revolved around finding, acquiring and using political and legislative data for journalism. That meant [scraping web sites for congressional data](https://github.com/dwillis/statement), building [APIs](https://projects.propublica.org/api-docs/congress-api/) and helping my colleagues build [interactives that explore important issues](https://projects.propublica.org/represent/). I used to [appear on C-SPAN](https://www.c-span.org/person/?57627/DerekWillis) once in awhile, too.

### ProPublica, 2015-2021

As a news applications developer, I both built data-driven websites and wrote articles. [Read them here](https://www.propublica.org/people/derek-willis).

Some of my favorite work:

 * [Hundreds of PPP Loans Went to Fake Farms in Absurd Places](https://www.propublica.org/article/ppp-farms)
 * [New Records Show the NYPD’s Favored Punishment: Less Vacation Time](https://projects.propublica.org/nypd-disciplinary-records/)
 * [The NYPD Files](https://projects.propublica.org/nypd-ccrb/)
 * [Tracking PPP Loans](https://projects.propublica.org/coronavirus/bailouts/)
 * [How Fundraisers Convinced Conservatives to Donate $10 Million — Then Kept Almost All of It](https://www.propublica.org/article/conservative-majority-fund-political-fundraising-pac-kelley-rogers)
 * [How Congress Stopped Working](https://www.propublica.org/article/how-congress-stopped-working)
 * [Represent](https://projects.propublica.org/represent/)
 * [FEC Itemizer](https://projects.propublica.org/itemizer/)
 
### The New York Times, 2007-2015
 
 As a interactive news developer and later a writer on The Upshot, I was a member of The Times' first newsroom web development team and later wrote data-driven stories. [Read some of them here](https://www.nytimes.com/by/derek-willis). I also helped produce two public APIs for congressional and campaign finance data.
 
Some of my favorite work:

 * [Maiden Names, on the Rise Again](https://www.nytimes.com/2015/06/28/upshot/maiden-names-on-the-rise-again.html)
 * [How ActBlue Became a Powerful Force in Fund-Raising](https://www.nytimes.com/2014/10/09/upshot/how-actblue-became-a-powerful-force-in-fund-raising.html)
 * [Looking for John McCain? Try a Sunday Morning Show](https://www.nytimes.com/2014/09/06/upshot/looking-for-john-mccain-try-a-sunday-morning-show.html)
 * [Voting Totals Reveal Crucial Boost From Blacks in Thad Cochran’s Victory](https://www.nytimes.com/2014/07/10/upshot/voting-totals-reveal-crucial-boost-from-blacks-in-cochrans-victory.html)
 * [A Mysterious Republican Committee in the Virgin Islands](https://www.nytimes.com/2014/05/07/upshot/a-mysterious-republican-committee-in-the-virgin-islands.html)
 * [Freeing the Plum Book](https://archive.nytimes.com/open.blogs.nytimes.com/2013/01/15/freeing-the-plum-book/)
 * [Outside Spending in Key House Races](https://archive.nytimes.com/www.nytimes.com/interactive/2012/10/25/us/politics/outside-spending-in-key-house-races.html)
 * [The 2012 Money Race: Compare the Candidates](https://www.nytimes.com/elections/2012/campaign-finance.html)
 * [Represent](https://archive.nytimes.com/open.blogs.nytimes.com/2008/12/22/represent/)
 * [Toxic Waters](https://www.nytimes.com/interactive/projects/toxic-waters/contaminants/index.html)
 
### The Washington Post/washingtonpost.com, 2004-2007
 
 I started at the Post as a research database editor, contributing to stories, and then moved to washingtonpost.com (then a separate company!) to build data-driven projects.
 
 Some of my favorite work:
 
 * [D.C. Red-Light Cameras Fail to Reduce Accidents](https://www.washingtonpost.com/archive/politics/2005/10/04/dc-red-light-cameras-fail-to-reduce-accidents/eb72bf0c-37f7-4089-bace-75e73043d60a/)
 * [Gulf Firms Losing Cleanup Contracts](https://www.washingtonpost.com/archive/business/2005/10/04/gulf-firms-losing-cleanup-contracts/ebce5e7a-cd10-4749-96cb-7674d7d6da93/)
 * [Hill Leaders Often Take Corporate Jets](https://www.washingtonpost.com/wp-dyn/content/article/2005/05/04/AR2005050402393.html)
 * [The U.S. Congress Votes Database](https://web.archive.org/web/20060215191153/http://projects.washingtonpost.com/congress/)
 
### The Center for Public Integrity, 2003-2004

As a database editor and writer, I contributed to several projects by building databases and writing some stories. [Read them here](https://publicintegrity.org/author/derek-willis/).

Some of my favorite work:

* [Silent Partners](https://publicintegrity.org/politics/silent-partners-special-report/)

### Congressional Quarterly, 1998-2003

### The Palm Beach Post, 1995-1997