---
title: The Difference
date: 2008-09-21
author: "Derek Willis"
format:
  html:
    df-print: paged
    toc: true
engine: knitr
---

One of the things I try to stress to students in my computer-assisted reporting class at GW each spring is the difference between a story based largely on anecdotes or temporal observation and the same story with the addition of a definitive analysis of data. The [LIRR story in today's Times by Walt Bogdanich, Andy Lehren and a host of contributors](http://www.nytimes.com/2008/09/21/nyregion/21lirr.html) is a great example of the latter.

There's little doubt that a good reporter who looked hard enough at the LIRR would start to learn that disability payments for retirees were more frequent than one might expect. Tales about people retiring and getting huge disability payments, as the story details. You'd be able to get the pictures of folks receiving large disability payments playing golf, as the reporters on this story did. But nailing the story - removing any doubt that this isn't a handful of isolated cases - takes the kind of analysis that Andy Lehren did. The kind that leads to a reporter being able to write this:

"Virtually every career employee - as many as 97 percent in one recent year - applies for and gets disability payments soon after retirement."

Case closed. Airtight. Dare I say George Tenet might trot out "slam dunk" again for this one. My only quibble is that Andy didn't get a byline. Congrats to Andy, Walt and the rest of my colleagues who worked on this. And for showing the difference that good data analysis can make to journalism.
