---
title: The Best Training
date: '2018-04-04T21:20:05-04:00'
author: "Derek Willis"
format:
  html:
    df-print: paged
    toc: true
engine: knitr
---

I've been asked by students what the best training is to be a journalist. My position on this is very clear: waiting tables at a honeymoon resort is the best training.

No, really, that's it. After you've delivered breakfast in bed to people who arrived late the night before, probably hammered, and now in the early morning can't find the door, much less their pants, you can pretty much deal with any sort of situation that requires human interaction.

Interviewing strangers can be hard. But most of them are at least wearing some clothes, which reduces the awkwardness, you know?

I spent four summers and various holidays at a honeymoon resort in the Pocono Mountains of Pennsylvania, one of the places with those giant fiberglass jacuzzis shaped like champagne glasses. Should you go, please listen carefully: the instructions say you put a CAP-ful of bubble bath into the jacuzzi. Because it's a jacuzzi, not a bath for an infant. If you pour the whole bottle in, you get that TV commercial where the bubbles grow eyes and fan out across the floor like an invading army. Housekeeping will hate you even more, and that's an achievement for people who are cleaning up after you and your beloved have tried out the place, if you know what I mean. One cap-ful. I can't set the breakfast tray down if the table is covered by 3 feet of bubbles.

Here's how it works: I'd drive a golf cart equipped with a tray-carrying back up to your door, grab the trays and start knocking. You could always tell if a couple was new because you'd hear them crashing into unfamiliarly-placed furniture on their way downstairs. There are windows in some of these rooms, but generally honeymoon resorts aren't the place where you want an audience. When the man (it's almost always the man) opens the door, he usually realizes two things: one, that the presence of sunlight has temporarily blinded him, and two, that there is an ACTUAL PERSON standing there with breakfast. He immediately tries to hide his body behind the door.

That's a pretty smart play, with one flaw: the walls of the place are covered in mirrors. Ain't no hiding place here, buddy, and I can see that I won't be getting a tip because YOU HAVE NO PANTS ON.

There are two approaches here: you can do the silent nod, drop off the tray and get out of there as quickly as possible. That's the route most newbies take, because I mean, it makes sense. Why would you want to hang around and chat? But that's what the veterans know: the cheerier you are - "GOOOOD MORNING!" - and the longer you linger, the better the chance that you turn the awkward tables on your already uncomfortable hosts. You do this all the time - they don't. That's when you gotta do the small talk, asking how their stay has been, whether they've used the jacuzzi yet, or just saying how nice it is outside. After a few seconds, you can tell if he's going to go back upstairs and get some money or not.

The only real risk with lingering is that you get asked to play photographer. Yes. That is a thing. Ok, it's not a naked thing, but it's still a thing. Sometimes people want to have their picture taken on the bed, because it's a round bed and, really, when are you going to be lying in a round bed again? The photo session is high on the discomfort factor, but if you stick it out you almost always get a tip. And you've definitely entitled to give the head nod when the couple arrives for dinner that evening. No waving, though. That's just weird.

Repeat that process 15-20 times a morning for three months and I assure you that approaching complete strangers to talk is nothing, even if you're asking some pretty personal questions.

That's the best training. There may be some long-term side effects.
