---
title: Better Tools
date: "2007-05-19"
author: "Derek Willis"
format:
  html:
    df-print: paged
    toc: true
engine: knitr
---

_Tenth in a series of essays humbly titled "Fixing Journalism"_

Journalists – Walt Mossberg and most of my fellow CAR geeks aside – aren't known for their early adoption of technology. You see quite a few typewriters in newsrooms, not being used, of course, but as a reminder of simpler times. They're like comfort food for folks who haven't really become adjusted to the changes in our culture and industry. They could also be considered museum pieces, which is what they really are.

Given the tools reporters and editors have had to learn and then ditch a few years later – I'm thinking of [ATEX terminals](http://q.queso.com/archives/001053), "custom" editing and layout systems and the like – it's not a surprise that journalists aren't always eager to use the next best thing. Or even the pretty good thing. But the tools for reporting and analysis have improved so much and become so accessible that we are falling behind in the race for more insightful and original stories. Worse, our competition pool is growing as people equipped with cheaper and more powerful tools compile information that should be in our domain.

[I've written before](http://www.thescoop.org/thefix/the-collaboration-issue/) about the state of a typical newsroom: some of the most valuable information will be stored in a reporter or editor's account on the publishing system. This might be a Rolodex file of sources or beat responsibilities or interview notes. Some of it might be in Word files scattered around individual PCs. Some of it might even live in individual spreadsheets or Access databases on a network drive accessible by everyone. And some of it might reside in centralized database servers or in software controlled by certain departments.

None of these are a perfect solution, but one thing is clear: the days of using Word, let alone your newsroom's editing system, as a repository of information are past. Word has its uses, but they mostly deal with the ability to use bold or italics. Actually, there is one very good use for Word – introducing reporters to the concept of pattern-matching, since [Word's search and replace function](http://www.datamystic.com/textpipe/htmlhelp/replace%20menu/wordpattern.htm) is probably its best feature. If you have text – words and numbers – store them in a text editor or a structured repository like a spreadsheet or a database. Using Word to store information [can be considered harmful to journalism](http://www.oreillynet.com/onjava/blog/2003/09/word_considered_harmful.html). If you use Word or WordPerfect or some other word processor to store your contacts, notes and other details, you need to stop doing this and move onto something better.

So what to use? How about a wiki, or maybe a content management system that stores information in a database. Make structured what needs to be retrieved often – important dates, figures and texts. Think of it this way: your newsroom probably stores its photographs in a database of some kind (if not, you've got an even bigger problem). Why should your raw information be harder to find, explore and share?

Let's start with something almost every newsroom covers: homicides. Unless your newsroom has an odd definition of news, murders usually warrant some coverage. The papers I have worked for have always done an annual "this year in homicide" story, usually around the 1st of the new year. "Last year [some number] people were murdered in our [city/county/area], an [increase/decrease] from the previous year." And so it goes. While we should have something to say on whether murder is rising or falling, in my experience too many of these stories are thrown together in the final weeks of December so that all the reporter really can do is a big-picture overview. Because this annual story sometimes involves multiple reporters who originally covered some of the murders, it's hard to write with authority.

What if, in addition to asking the police department about homicides in December, we actually gathered and stored information throughout the year as murders occurred? By the end of the year the reporter would have a ready-to-go database and, with any luck, had spent some time with it – even if that only meant some data entry – in the prior months. It's much more efficient than an archive search and much more likely to allow for some deeper analysis. But that's only possible if we use better tools.

I pick on Microsoft and its products a lot, but Excel is a great tool. It's accessible to most people and serves as a sort of "gateway drug" to more robust tools. Plus, it's pretty powerful itself. I know folks who could practically live inside Excel, data-wise. So if the idea of putting information into a database scares you, or your newsroom doesn't really get why anybody would want a browser-based front end to a database system, use a spreadsheet to store information. And always think about what you can do with that information.

As long as I've taught a class on CAR, I've taught only Microsoft Access as a database manager. That ends now. I cannot recommend it any longer as a proper tool for reporters serious about working with data on a regular basis. The main reason is lock-in: in order to read Access files you need Access (or you can have your fun with ODBC, I suppose). The secondary reason, which will only become more important, is that when it comes to the Web, Access does nothing for you. It's slow, only runs on Windows and has a relatively low file size limit compared to other databases. Access files seem to grow exponentially, a problem not unique to Access, but still a problem.

Access has two things going for it: it's usually in the newsroom already, and it's a known entity with lots of menus and wizards. The first is purely an accident of corporate software purchasing habits, and the second actually can make interacting with a database more confusing, not less. Chances are that if you have data in Access and want to do something with it on the Web, you'll need to get the data out of Access and into something else. It doesn't fit into the "information wants to be free" theory very well at all.

If not Access, then what? For work purposes, I've already switched to higher-end databases like SQL Server, MySQL and PostgreSQL. But in my CAR class this semester I briefly introduced [SQLite](http://www.sqlite.org/) and will use that next year. It runs on any system, is highly portable and a true SQL-based database. It also plays well with the Web and is free. Yes, I suppose there will be times when I think about the "crosstab query wizard" in Access, but already those occur less often than I anticipated. Don't trade surface ease-of-use for power and flexibility.

When it came time for my students to work on group projects, several of them chose to do their spreadsheet work using Google Docs, which made for more efficient use of time and also eliminated the need to email various versions of the data to each other. Now, I know full well that most news organizations are not going to approve of reporters putting sensitive material on Google's servers, but the point is that you don't have to work in the same way you did 5 or 10 years ago. Not using better tools isn't showing some kind of stubborn respect for your tradition. It's stupidity.

Information is literally trapped in newsroom applications just because we've been reluctant (or worse, ignorant) of the existence of better tools to do our jobs. At a time when journalism is being challenged by [individuals who build useful tools in their spare time](http://www.govtrack.us/), most of us continue to work with the kind of constraints that no serious business would tolerate. If we cannot harness our expertise and vast stores of information and put them to better use than a 25-year-old with a good idea and some spare server capacity, then we deserve to be punished by the market.

How to get better tools in the hands of reporters and editors? Well, this one has always been something of a mystery to me, since journalists are inquisitive people. Unfortunately that usually doesn't extend to the tools they use unless you can demonstrate clearly the benefits of adopting a new piece of software or equipment. That's why newsrooms need people who are not just trainers but evangelists for better tools. And they need to get serious about requiring basic levels of proficiency from the people they hire. My students tell me that editors they interview with get really excited when they mention that they've taken a class in basic computer-assisted reporting methods. We need to get to the point where this is not a delightful surprise but an expectation.

The basic way that journalists gather information – reading, calling, interviewing, researching – will not go away, and this isn't an attempt to argue that they should. Rather, it's a suggestion that we need to start doing all of those things better, not just because we face greater competition for news, but because we can. That we have better tools and do not use them may not be apparent to our readers right now, but will be soon enough. Let's not wait for that day, because it won't be a happy one for any of us.